name: Shipwright Tokens
description: Automates style generation from a Shipwright design
author: Headwayio
branding:
  icon: "anchor"
  color: "blue"
inputs:
  styleSystem:
    description: 'Which pre-configured style library output do you want, defaults to "mui" (options: ["mui","tailwind","mobile"])'
    required: false
    default: "mui"
  tokenFile:
    description: 'Relative path to your tokens.json file output from the Figma Tokens plugin. Default: "tokens/tokens.json"'
    required: false
    default: "tokens/tokens.json"
  outputFolder:
    description: 'Relative path to your tokens.json file output from the Figma Tokens plugin. Default: "tokens/tokens.json"'
    required: false
    default: "output"
  #TODO: Build path configuration for style-dictionary

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
    - run: npx token-transformer ${{ inputs.tokenFile }} ${{ inputs.outputFolder }}/tokens.json
      shell: bash
    - run: npx style-dictionary build --config ${{ github.action_path }}/configs/${{ inputs.styleSystem }}.json
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updated style Shipwright tokens
