name: Shipwright Tokens
description: Automates style generation from a Shipwright design
author: Headwayio
branding:
  icon: "anchor"
  color: "blue"
inputs:
  styleSystem:
    description: 'Which pre-configured style library output do you want, defaults to "mui" (options: ["mui","tailwind","mobile"])'
    required: false
    default: "mui"
  tokenFile:
    description: 'Relative path to your tokens.json file output from the Figma Tokens plugin. Default: "tokens/tokens.json"'
    required: false
    default: "tokens/tokens.json"
  tokenOutputFolder:
    description: 'Relative path to your tokens.json file output from the Figma Tokens plugin. Default: "tokens/tokens.json"'
    required: false
    default: "output"
  styleOutputFolder:
    description: 'Relative path to your styles output directory. Default: "build"'
    required: false
    default: "build"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
    - run: npm install --prefix ${{ github.action_path }} style-dictionary
      shell: bash
    - run: node ${{ github.action_path }}/build-config.js ${{ inputs.styleOutputFolder }} ${{ inputs.tokenOutputFolder }}
      shell: bash
    - run: npx token-transformer ${{ inputs.tokenFile }} ${{ inputs.tokenOutputFolder }}/tokens.json --expandTypography=true --expandComposition=true --preserveRawValue=false --resolveReferences=true
      shell: bash
    - run: node ${{ github.action_path }}/build.js
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updated style Shipwright tokens
