name: Shipwright Tokens
description: Automates style generation from a Shipwright design
author: Headwayio

# on:
#   push:
#     branches:
#       - main
# jobs:
#   generate-build-number-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Setup Node.js environment
#         uses: actions/setup-node@v2.4.0
#       - run: npm install
#       - run: npm run build
#       - uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#           commit_message: automated change

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
    - run: npx token-transformer tokens/tokens.json output/tokens.json
      shell: bash
    - run: npx style-dictionary build
      shell: bash
    - run: npx postcss ./styles.css -o ./tailwind.css
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: automated change
