name: Shipwright Tokens

on:
  push:
    branches:
      - 'tokens/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Shipwright Tokens
        uses: headwayio/shipwright-tokens@main
        with:
          styleSystem: mui
          tokenFile: styles/tokens/tokens.json
          outputFolder: styles/mui

