name: Automatically merge Dependabot PRs

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  automate-dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.dependabot }}
